version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Containerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus

volumes:
  prometheus-data:
    external: true